/**
 * ForgeEnv - Environment and Variable Management for Generated API Clients
 * 
 * Lightweight runtime for Playwright API clients generated by @http-forge/codegen.
 * Provides variable storage, template resolution, and URL building capabilities.
 * 
 * @example
 * ```typescript
 * import { ForgeEnv } from '@http-forge/playwright';
 * 
 * const env = ForgeEnv.create({
 *     baseUrl: 'https://api.example.com',
 *     apiKey: 'secret123',
 * });
 * 
 * // Template resolution
 * env.resolve('{{baseUrl}}/users');  // 'https://api.example.com/users'
 * 
 * // Build URL with path params and query
 * env.buildUrl('{{baseUrl}}/users/:id', { 
 *     params: { id: '123' },
 *     query: { include: 'profile' }
 * });
 * ```
 */

/**
 * ForgeEnv interface - Public API for environment management
 */
export interface IForgeEnv {
    /** Get a variable value */
    get(key: string): string | undefined;

    /** Set a variable value */
    set(key: string, value: string): void;

    /** Check if a variable exists */
    has(key: string): boolean;

    /** Delete a variable */
    delete(key: string): void;

    /** Get all variables */
    getAll(): Record<string, string>;

    /** Get the active environment name (e.g., 'dev', 'sit', 'prod') */
    getActiveEnvironment(): string | undefined;

    /** Set the active environment by name */
    setActiveEnvironment(name: string): void;

    /** Get list of available environment names */
    getEnvironments(): string[];

    /** Resolve {{variable}} placeholders in a string */
    resolve(template: string): string;

    /** Resolve {{variable}} and :pathParam placeholders in a URL */
    resolvePath(urlPattern: string, params?: Record<string, string>): string;

    /** Build a complete URL with variables, path params, and query params */
    buildUrl(
        urlPattern: string,
        options?: {
            params?: Record<string, string>;
            query?: Record<string, string>;
        }
    ): string;

    /** Resolve variables in an object recursively (deep) */
    resolveObject<T>(obj: T): T;

    /** Extract variable names from a template string */
    extractVariables(template: string): string[];

    /** Extract path parameter names from a URL pattern */
    extractPathParams(urlPattern: string): string[];
}

/**
 * Variable Interpolator - Replaces {{variable}} patterns
 */
class VariableInterpolator {
    private readonly variablePattern = /\{\{(\w+)\}\}/g;

    /** Escape special characters for use in quoted strings */
    private escapeForString(value: string, quoteChar: '"' | "'"): string {
        let escaped = value.replace(/\\/g, '\\\\');
        
        if (quoteChar === '"') {
            escaped = escaped.replace(/"/g, '\\"');
        } else {
            escaped = escaped.replace(/'/g, "\\'");
        }
        
        return escaped
            .replace(/\n/g, '\\n')
            .replace(/\r/g, '\\r')
            .replace(/\t/g, '\\t');
    }

    /** Determine if position is inside a quoted string */
    private getStringContext(input: string, position: number): '"' | "'" | null {
        let currentQuote: '"' | "'" | null = null;
        
        for (let i = 0; i < position; i++) {
            const char = input[i];
            const prevChar = i > 0 ? input[i - 1] : '';
            
            if (prevChar === '\\') continue;
            
            if (char === '"' || char === "'") {
                if (currentQuote === null) {
                    currentQuote = char;
                } else if (currentQuote === char) {
                    currentQuote = null;
                }
            }
        }
        
        return currentQuote;
    }

    /** Replace {{variable}} placeholders with values */
    interpolate(input: string, variables: Record<string, string>): string {
        if (!input || typeof input !== 'string') return input;

        let result = '';
        let lastIndex = 0;
        const regex = /\{\{(\w+)\}\}/g;
        let match;

        while ((match = regex.exec(input)) !== null) {
            const varName = match[1];
            const value = variables[varName];
            
            if (value !== undefined) {
                result += input.slice(lastIndex, match.index);
                const quoteContext = this.getStringContext(input, match.index);
                result += quoteContext ? this.escapeForString(String(value), quoteContext) : String(value);
            } else {
                result += input.slice(lastIndex, match.index + match[0].length);
            }
            
            lastIndex = match.index + match[0].length;
        }
        
        result += input.slice(lastIndex);
        return result;
    }

    /** Extract variable names from a string */
    extractVariables(input: string): string[] {
        if (!input || typeof input !== 'string') return [];

        const variables: string[] = [];
        const pattern = /\{\{(\w+)\}\}/g;
        let match: RegExpExecArray | null;
        
        while ((match = pattern.exec(input)) !== null) {
            if (!variables.includes(match[1])) {
                variables.push(match[1]);
            }
        }

        return variables;
    }

    /** Replace variables in an object recursively */
    interpolateObject<T>(obj: T, variables: Record<string, string>): T {
        if (obj === null || obj === undefined) return obj;

        if (typeof obj === 'string') {
            return this.interpolate(obj, variables) as unknown as T;
        }

        if (Array.isArray(obj)) {
            return obj.map(item => this.interpolateObject(item, variables)) as unknown as T;
        }

        if (typeof obj === 'object') {
            const result: Record<string, any> = {};
            for (const [key, value] of Object.entries(obj)) {
                result[key] = this.interpolateObject(value, variables);
            }
            return result as T;
        }

        return obj;
    }
}

/**
 * URL Builder - Builds URLs with path params and query strings
 */
class UrlBuilder {
    constructor(private readonly interpolator: VariableInterpolator) {}

    /** Build complete URL with all substitutions */
    buildUrl(
        urlPattern: string,
        variables: Record<string, string>,
        params: Record<string, string> = {},
        query: Record<string, string> = {}
    ): string {
        let url = this.interpolator.interpolate(urlPattern, variables);
        url = this.replacePathParams(url, params);
        url = this.appendQueryParams(url, query, variables);
        return url;
    }

    /** Replace path parameters (:param, :param?, :param(regex)) */
    replacePathParams(url: string, params: Record<string, string>): string {
        let protocol = '';
        let host = '';
        let path = url;
        let query = '';

        const queryIndex = url.indexOf('?');
        if (queryIndex !== -1) {
            query = url.substring(queryIndex);
            path = url.substring(0, queryIndex);
        }

        const protocolMatch = path.match(/^(https?:\/\/)([^\/]*)(\/.*)?$/);
        if (protocolMatch) {
            protocol = protocolMatch[1];
            host = protocolMatch[2];
            path = protocolMatch[3] || '/';
        }

        const paramRegex = /:(\w+)(?:\([^)]*\))?(\?)?/g;

        let resultPath = path.replace(paramRegex, (match, paramName, isOptional) => {
            const value = params[paramName];

            if (value !== undefined && value !== '') {
                return encodeURIComponent(value);
            }

            if (isOptional) return '';

            console.warn(`[ForgeEnv] Missing required path parameter: ${paramName}`);
            return match;
        });

        resultPath = resultPath.replace(/([^:])\/+/g, '$1/');

        if (resultPath.length > 1 && resultPath.endsWith('/')) {
            resultPath = resultPath.slice(0, -1);
        }

        return `${protocol}${host}${resultPath}${query}`;
    }

    /** Extract path parameter names from URL pattern */
    extractPathParams(urlPattern: string): string[] {
        const paramRegex = /:(\w+)(?:\([^)]*\))?(\?)?/g;
        const params: string[] = [];
        let match;

        while ((match = paramRegex.exec(urlPattern)) !== null) {
            params.push(match[1]);
        }

        return [...new Set(params)];
    }

    /** Append query parameters to URL */
    private appendQueryParams(
        url: string,
        query: Record<string, string>,
        variables: Record<string, string>
    ): string {
        let pathWithoutQuery = url;
        let existingQueryParams: Record<string, string> = {};

        if (url.includes('?')) {
            const [basePath, queryString] = url.split('?');
            pathWithoutQuery = basePath;

            if (queryString) {
                const urlParams = new URLSearchParams(queryString);
                urlParams.forEach((value, key) => {
                    existingQueryParams[key] = value;
                });
            }
        }

        const mergedQuery = { ...existingQueryParams, ...query };

        const resolvedQuery: Record<string, string> = {};
        for (const [key, value] of Object.entries(mergedQuery)) {
            if (value !== undefined && value !== null && value !== '') {
                resolvedQuery[key] = this.interpolator.interpolate(value, variables);
            }
        }

        const queryParams = new URLSearchParams();
        for (const [key, value] of Object.entries(resolvedQuery)) {
            queryParams.append(key, value);
        }
        const queryString = queryParams.toString();

        return queryString ? `${pathWithoutQuery}?${queryString}` : pathWithoutQuery;
    }
}

/**
 * ForgeEnv implementation
 */
export class ForgeEnv implements IForgeEnv {
    private variables: Map<string, string>;
    private environments: Map<string, Record<string, string>>;
    private activeEnvironment?: string;
    private readonly interpolator: VariableInterpolator;
    private readonly urlBuilder: UrlBuilder;

    constructor(variables: Record<string, string> = {}) {
        this.variables = new Map(Object.entries(variables));
        this.environments = new Map();
        this.interpolator = new VariableInterpolator();
        this.urlBuilder = new UrlBuilder(this.interpolator);
    }

    // Variable Management
    get(key: string): string | undefined {
        return this.variables.get(key);
    }

    set(key: string, value: string): void {
        this.variables.set(key, value);
    }

    has(key: string): boolean {
        return this.variables.has(key);
    }

    delete(key: string): void {
        this.variables.delete(key);
    }

    getAll(): Record<string, string> {
        return Object.fromEntries(this.variables);
    }

    // Environment Management
    getActiveEnvironment(): string | undefined {
        return this.activeEnvironment;
    }

    setActiveEnvironment(name: string): void {
        const envVars = this.environments.get(name);
        if (envVars) {
            this.activeEnvironment = name;
            this.variables = new Map(Object.entries(envVars));
        }
    }

    getEnvironments(): string[] {
        return Array.from(this.environments.keys());
    }

    /** Add an environment */
    addEnvironment(name: string, variables: Record<string, string>): void {
        this.environments.set(name, variables);
    }

    // Template Resolution
    resolve(template: string): string {
        return this.interpolator.interpolate(template, this.getAll());
    }

    resolvePath(urlPattern: string, params: Record<string, string> = {}): string {
        return this.urlBuilder.buildUrl(urlPattern, this.getAll(), params);
    }

    buildUrl(
        urlPattern: string,
        options: {
            params?: Record<string, string>;
            query?: Record<string, string>;
        } = {}
    ): string {
        return this.urlBuilder.buildUrl(
            urlPattern,
            this.getAll(),
            options.params || {},
            options.query || {}
        );
    }

    resolveObject<T>(obj: T): T {
        return this.interpolator.interpolateObject(obj, this.getAll());
    }

    extractVariables(template: string): string[] {
        return this.interpolator.extractVariables(template);
    }

    extractPathParams(urlPattern: string): string[] {
        return this.urlBuilder.extractPathParams(urlPattern);
    }

    // Factory Methods
    static create(variables: Record<string, string> = {}): ForgeEnv {
        return new ForgeEnv(variables);
    }

    static fromEnvironments(
        environments: Record<string, Record<string, string>>,
        activeEnvironment?: string
    ): ForgeEnv {
        const env = new ForgeEnv();
        
        for (const [name, vars] of Object.entries(environments)) {
            env.addEnvironment(name, vars);
        }

        if (activeEnvironment && environments[activeEnvironment]) {
            env.setActiveEnvironment(activeEnvironment);
        } else if (Object.keys(environments).length > 0) {
            env.setActiveEnvironment(Object.keys(environments)[0]);
        }

        return env;
    }
}
